### ISSUE TITLE
data missing

### ISSUE THREAD

**Issue by DataStrategist** [artemyk/chordsentiment#1]
Hi, I just read your [article](https://royalsocietypublishing.org/doi/pdf/10.1098/rsos.170952) , and it looks great! I was wondering whether I could use your data (which should be here https://figshare.com/s/0ca9d1bdb8fd67896547 I think, but now 404s), with attibution of course?

**Comment by artemyk** [comment]
@DataStrategist sorry about that --- we had an outdated link in the README (and the article, unfortunately).  The correct link is at https://figshare.com/articles/The_Minor_Fall_the_Major_Lift_Inferring_Emotional_Valence_of_Musical_Chords_through_Lyrics/5413060/1 , and the git README is now updated.  Thanks for bringing this to our attention.

**Comment by DataStrategist** [comment]
Thanks for that! I was looking at teh data and it seems that not all of the lyrics made it to the dataset, I guess that's because of the problems described in the paper? I was hoping to do some chord-progression work but I suppose that's not possible using this dataset? Would you have (even dirty) versions of the full scrape?

**Comment by artemyk** [comment]
@DataStrategist I see the issue. Could you please contact me over email at artemyk@gmail.com ?
